codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "85...100"

  status:
    project:
      default:
        threshold: 3%
    patch: no
    changes: no

  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1% # allow coverage to drop by 1% without posting

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

