-
    branches:
      only:
        - /release.*/
        - master
    environment:
      matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python34"
        - PYTHON: "C:\\Python35"
    build: false
    cache:
        - C:\mingw64-> appveyor.yml
    install:
      - .ci/appveyor/install.bat
    test_script:
      - .ci/appveyor/test.bat
    after_test:
      - .ci/appveyor/after.bat

-
    environment:
      matrix:
        - PYTHON: "C:\\Python35"
    build: false
    cache:
        - C:\mingw64-> appveyor.yml
    install:
      - .ci/appveyor/install.bat
    test_script:
      - .ci/appveyor/test.bat
    after_test:
      - .ci/appveyor/after.bat
